### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by 532910** [ash/covid.observer#1]
You should define both foreground and background colors together, implicitly, or not define them at all. Really you shouldn't reproduce it (just define both fg and bg and don't rely on common defaults), but if you want, it is firefox with `browser.display.use_system_colors = true` and env `GTK_THEME=Adwaita:dark`

![image](https://user-images.githubusercontent.com/14617699/76705099-a1bd2a80-66ee-11ea-8ce3-67662fe0df35.png)

**Comment by ash** [comment]
Should be fine now.

**Comment by 532910** [comment]
ack (:
