### ISSUE TITLE
Hongkong and Macao show 0%

### ISSUE THREAD

**Issue by choroba** [ash/covid.observer#12]

**Comment by ash** [comment]
Thanks for noticing. Actually, this is about:

https://covid.observer/cn/hk/
https://covid.observer/cn/mo/

vs. 

https://covid.observer/hk/
https://covid.observer/mo/

Which reflects how the JHU categorises the numbers for these territories. I should collapse the data to a common bin.

**Comment by ash** [comment]
Solved in https://github.com/ash/covid.observer/commit/75f9422e0e013ae7bda0a3783dcfaba05ca67829.
