### ISSUE TITLE
Cumulative 14-day index - description misleading.

### ISSUE THREAD

**Issue by bbkr** [ash/covid.observer#19]
Currently it says this chart is used "to estimate how safe travelling is". Usually on safety charts higher is better, for example vehicle with 5 stars NCAP are safer that 3 stars NCAP.

Therefore some people may misinterpret it. It should say "to estimate how unsafe travelling is". Or have some note like "to estimate how safe travelling is (higher is less safe)".

**Comment by ash** [comment]
Thanks. Updated in edd46c3a593723dc4a7a8aca8617290752ac9200
