### ISSUE TITLE
Сломалась статистика по Москве

### ISSUE THREAD

**Issue by MichaelMonashev** [ash/covid.observer#22]
Тут странные цифры показываются https://covid.observer/ru/77/

**Comment by MichaelMonashev** [comment]
И тут тоже та же проблема https://covid.observer/ru/

**Comment by ash** [comment]
https://github.com/ash/covid.observer/commit/bd518eb232fa64003215480f85f503b0c9e26df9

**Comment by MichaelMonashev** [comment]
Тут https://covid.observer/ru/ и тут https://covid.observer/ru/50/ проблемы остались.

**Comment by ash** [comment]
И 0548ffd45c9f21c45eefd35f91a237598581a104
