### ISSUE TITLE
Independent territories of various countries

### ISSUE THREAD

**Issue by waterkip** [ash/covid.observer#7]
In #6 I've splitted the Netherlands to exclude the independent territories, France, Denmark and the UK have similar situations. Want me to split those up as well?

**Comment by ash** [comment]
Yes, I made a note for myself for other countries like NL. I will do it later tonight or tomorrow, or you can be quicker to propose a pull request. Actually, it is a bit more work then only filtering the JHU's data: https://github.com/ash/covid.observer/commit/48b36f2548d0a4d72dd97148c1d6243407c131e4

**Comment by waterkip** [comment]
Yes I saw your additional changes. St Maarten is a funny thing because half of it is owned by France: Sint Martinque. I haven't checked if they split the numbers in between the two parts of the island or if both are using the same numbers.

I did not have a running env for this nor did I see instructions on getting a working env. I can try to do it.

**Comment by ash** [comment]
Hi @waterkip, the source data were significantly changed yesterday (no recoveries anymore), so I switched to daily reports. Just in case you wanted to contribute, the old parser is not actual anymore.

**Comment by ash** [comment]
(Mostly) solved in 5e24c300b7a3711ac1f487f56b87c88440c8332d.
